In [1]:
import numpy as np
import pandas as pd
from datetime import datetime, date, time
from sklearn.model_selection import train_test_split

In [2]:
def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [3]:
vibro = pd.DataFrame()
vibroDF = pd.DataFrame()

In [4]:
vibro = pd.read_csv('Vibro.csv',sep=';')

In [5]:
for i in range(0, 9000):
    a = datetime.strptime(vibro['Tag_Date'][i],"%d.%m.%Y %H:%M:%S")
    vibroDF.loc[i,'Tag_Date'] = a.timestamp()
    vibroDF.loc[i,'Tag_Value'] = vibro['Tag_Value'][i]

In [6]:
for i in range(0, 9000):
    a = datetime.strptime(vibro['Tag_Date'][i],"%d.%m.%Y %H:%M:%S")
    vibroDF.loc[i,'Tag_Date'] = a.timestamp()
    vibroDF.loc[i,'Tag_Value'] = vibro['Tag_Value'][i]

(vibroDF['Tag_Value'][0])<20

True

In [7]:
b = a.timestamp()
datetime.fromtimestamp(b)

datetime.datetime(2017, 8, 25, 18, 3, 49)

In [20]:
vibroDF['Cov'] = 0
for i in range(0, len(vibroDF)):
    if(int(vibroDF['Tag_Value'][i])>=6.0):
        vibroDF.loc[i,'Cov'] = 1
        print(i)
print(vibroDF[1636:1800])

1636
1637
1638
1758
1759
1760
1761
1762
1763
1764
1765
1766
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1785
1786
1787
1788
1790
1791
1792
1793
1794
1797
1798
1799
1800
1802
1817
1839
1840
1969
1970
1971
1972
1973
1974
1975
1976
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1995
1996
2000
2001
2002
2006
2011
2012
2013
2027
2055
2056
2065
2066
2077
2078
2085
2382
2387
2391
2392
2396
2397
2398
2404
2405
2406
2413
2420
2671
2676
2698
2699
2732
2733
2738
2741
2792
2865
2874
2882
2975
3822
6479
7243
7431
7468
7493
7494
7518
7558
7820
7832
7894
8022
8074
8082
          Tag_Date  Tag_Value  Cov
1636  1.503653e+09   7.266606    1
1637  1.503653e+09   7.632254    1
1638  1.503653e+09   7.512660    1
1639  1.503653e+09   2.647084    0
1640  1.503653e+09   5.285013    0
1641  1.503653e+09   1.924944    0
1642  1.503653e+09   2.098898    0
1643  1.503653e+09   4.080492    0
1644  1.503653e+09   2.162987    0
1645  1.503653e+09   0.719279    0
1646  1.503653e+09  

In [157]:
vibroDF.to_csv('V_01')

In [46]:
PX = np.array([vibroDF['Tag_Value'][1750:1800],vibroDF['Tag_Value'][1750:1800]]).T
PY = np.array([vibroDF['Cov'][1750:1800]]).T

In [51]:
# сделаем случайные числа более определёнными
np.random.seed(1)

# инициализируем веса случайным образом со средним 0
syn0 = 2*np.random.random((2,3))-1
syn1 = 2*np.random.random((3,1))-1
print(syn0)
print(syn1)

for iter in range(10000):

    # прямое распространение
    l0 = PX
    l1 = sigmoid(np.dot(l0,syn0))
    l2 = sigmoid(np.dot(l1,syn1))

    # насколько мы ошиблись?
    l2_error = PY - l2
    
    # перемножим это с наклоном сигмоиды 
    # на основе значений в l1
    l2_delta = l2_error*sigmoid(l2,deriv=True)
    
    # как сильно значения l1 влияют на ошибки в l2?
    l1_error = l2_delta.dot(syn1.T)
    
    # в каком направлении нужно двигаться, чтобы прийти к l1?
    # если мы были уверены в предсказании, то сильно менять его не надо
    l1_delta = l1_error * sigmoid(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

print ("Выходные данные после тренировки:")
print (l1)

[[-0.16595599  0.44064899 -0.99977125]
 [-0.39533485 -0.70648822 -0.81532281]]
[[-0.62747958]
 [-0.30887855]
 [-0.20646505]]
Выходные данные после тренировки:
[[1.81220154e-017 1.85396844e-057 6.11091154e-057]
 [1.70481603e-008 4.74196114e-027 8.24737459e-027]
 [7.93024685e-006 5.19439152e-018 7.47058262e-018]
 [6.48989798e-023 6.51147826e-076 3.16362947e-075]
 [1.88417494e-029 4.58933652e-098 3.55237839e-097]
 [8.18959053e-024 5.85295739e-079 3.03177078e-078]
 [6.78697106e-021 4.53760601e-069 1.90919316e-068]
 [2.18909389e-029 7.62950897e-098 5.87828075e-097]
 [1.29591876e-035 6.01331070e-119 7.22032389e-118]
 [1.25928976e-046 2.89658846e-156 7.62190212e-155]
 [1.25959374e-048 4.84131803e-163 1.46898865e-161]
 [5.40571265e-062 2.44199154e-208 1.92041762e-206]
 [1.01533997e-064 1.41089746e-217 1.34740742e-215]
 [4.00177031e-056 1.89243225e-188 9.79643921e-187]
 [9.19796817e-054 1.90146185e-180 8.31899392e-179]
 [7.78763313e-042 4.98660960e-140 9.32687476e-139]
 [2.64277522e-036 2.74915

In [38]:
def think(inputs):
    return sigmoid(np.dot(inputs,syn1))

In [39]:
test1 = np.array([6.255])

In [40]:
print(think(test1))

[0.99509974]


In [155]:
import numpy as np

def nonlin(x,deriv=False):
	if(deriv==True):
           return x*(1-x)
	return 1/(1+np.exp(-x))
    
X = np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
                
y = np.array([[0,1,1,0]]).T

np.random.seed(1)

# случайно инициализируем веса, в среднем - 0
syn0 = 2*np.random.random((3,3)) - 1
syn1 = 2*np.random.random((3,1)) - 1

for j in range(10000):

	# проходим вперёд по слоям 0, 1 и 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    # как сильно мы ошиблись относительно нужной величины?
    l2_error = y - l2
    
    # в какую сторону нужно двигаться?
    # если мы были уверены в предсказании, то сильно менять его не надо
    l2_delta = l2_error*nonlin(l2,deriv=True)

    # как сильно значения l1 влияют на ошибки в l2?
    l1_error =  l2_delta.dot(syn1.T)
    
    # в каком направлении нужно двигаться, чтобы прийти к l1?
    # если мы были уверены в предсказании, то сильно менять его не надо
    l1_delta = l1_error* nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

In [156]:
def think2(inputs):
    return nonlin(inputs.dot(syn1))
test2 = np.array([1,1,1])
print(think2(test2))

[0.18830477]
